version: '3.8'
services:
  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
    - "8080:8080"
    - "50051:50051"

    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - weaviate_data:/var/lib/weaviate
volumes:
  weaviate_data:
